apiVersion: apps/v1
kind: Deployment
metadata:
  name: testweb-app1
  labels:
    app: testweb-app1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: testweb-app1
  template:
    metadata:
      labels:
        app: testweb-app1
    spec:
      containers:
        - name: container10
          image: anshuman01/test-image
          ports:
            - containerPort: 3000
          resources:
            limits:
              cpu: 500m
            requests:
              cpu: 200m
          readinessProbe:
            httpGet:
              path: /health
              port: 3000
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /health
              port: 3000
            initialDelaySeconds: 15
            periodSeconds: 20
---
# apiVersion: autoscaling/v2beta2
# kind: HorizontalPodAutoscaler
# metadata:
#   name: testweb-app1
# spec:
#   scaleTargetRef:
#     apiVersion: apps/v1
#     kind: Deployment
#     name: testweb-app1
#   minReplicas: 1
#   maxReplicas: 10
#   metrics:
#     - type: Resource
#       resource:
#         name: cpu
#         targetAverageUtilization: 50
