apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment1
  labels:
    app: testweb-app2
spec:
  replicas: 2
  selector:
    matchLabels:
      app: testweb-app2
  template:
    metadata:
      labels:
        app: testweb-app2
    spec:
      containers:
        - name: container1
          image: anshuman01/test-image3
          ports:
            - containerPort: 3000
          # readinessProbe:
          #   httpGet:
          #     path: /health
          #     port: 3000
          #   initialDelaySeconds: 5
          #   periodSeconds: 10
          # livenessProbe:
          #   httpGet:
          #     path: /health
          #     port: 3000
          #   initialDelaySeconds: 15
          #   periodSeconds: 20
