apiVersion: v1
kind: Service
metadata:
  name: nodeport-service
  labels:
    app: testweb-app
spec:
  type: NodePort
  ports:
    - name: http
      port: 80
      targetPort: 3000
      nodePort: 30080
  selector:
    app: testweb-app
