apiVersion: v1
kind: Service
metadata:
  name: loadbalancer-service
  labels:
    app: testweb-app
spec:
  type: LoadBalancer
  ports:
    - name: http
      port: 82
      targetPort: 3000
  selector:
    app: testweb-app
